# Lab 3.1 Naive Bayes Classification and Sentiment Analysis


**1. Train two models, multinomial naive Bayes and binarized naive Bayes, both with
add-1 smoothing, on the following document counts for key sentiment words, with
positive or negative class assigned as noted.**

```
doc ”good” ”poor” ”great” (class)
d1. 3 0 3 pos
d2. 0 1 2 pos
d3. 1 3 0 neg
d4. 1 5 2 neg
d5. 0 2 0 neg
```

**Use both naive Bayes models to assign a class (pos or neg) to this sentence:
A good, good plot and great characters, but poor acting.
Do the two models agree or disagree?**

They disagree


In [2]:
import numpy as np

In [5]:
# Add-one smoothing
log_p_neg_sentence = np.log(3/5) + np.log(3/17) + np.log(3/17) + np.log(3/17) + np.log(11/17)
log_p_pos_sentence = np.log(2/5) + np.log(4/12) + np.log(4/12) + np.log(6/12) + np.log(2/12)


print(log_p_neg_sentence)
print(log_p_pos_sentence)

classes = ["neg", "pos"]


estimated_class = np.argmax(np.array([log_p_neg_sentence, log_p_pos_sentence]))
print(estimated_class,  classes[estimated_class])

-6.149946861188155
-5.598421958998374
1 pos


In [6]:
# Binaryzed Naive Bayes

log_p_neg_sentence = np.log(3/5) + np.log(3/9) + np.log(3/9) + np.log(2/9) + np.log(4/9)
log_p_pos_sentence = np.log(2/5) + np.log(2/8) + np.log(2/8) + np.log(3/8) + np.log(2/8)


print(log_p_neg_sentence)
print(log_p_pos_sentence)

classes = ["neg", "pos"]


estimated_class = np.argmax(np.array([log_p_neg_sentence, log_p_pos_sentence]))
print(estimated_class,  classes[estimated_class])

-5.023057814094814
-6.056003068245553
0 neg


**Consider an NLP classification task where a model is trained to classify text docu
ments into two categories: pos and neg. After testing the model on a validation set,
the following confusion matrix was obtained:**

```
Actual / Predicted      pos neg
                    pos 80 20
                    neg 30 70
```

**Based on the confusion matrix provided above, calculate the accuracy, and the pre-
cision, recall and F1 for the pos class. Provide your answers in decimal form rounded
to two decimal places**

In [25]:
accuracy = (80+70)/200

precision = 80/(80+20)

recall = 80/(80+30)

f1 = 2 * (precision * recall) / (precision + recall)

print("accuracy: ", accuracy)
print("precision: ", precision)
print("recall: ", recall)
print("f1: ", f1)

accuracy:  0.75
precision:  0.8
recall:  0.7272727272727273
f1:  0.761904761904762


In [29]:
import numpy as np

def calculate_metrics(confusion_matrix):
    # Calculate true positives, false positives, and false negatives for each class
    accuracy = (confusion_matrix[0,0] + confusion_matrix[1,1]) / np.sum(confusion_matrix)

    precision = confusion_matrix[0,0] / (confusion_matrix[0,0] + confusion_matrix[0,1])

    recall = confusion_matrix[0,0] / (confusion_matrix[0,0] + confusion_matrix[1,0])

    f1_score = 2 * (precision * recall) / (precision + recall)

    print("accuracy: ", accuracy)
    print("precision: ", precision)
    print("recall: ", recall)
    print("f1: ", f1_score, "\n")

    return accuracy, precision, recall, f1_score

calculate_metrics(np.array([[80, 20], [30, 70]]))

accuracy:  0.75
precision:  0.8
recall:  0.7272727272727273
f1:  0.761904761904762 



(0.75, 0.8, 0.7272727272727273, 0.761904761904762)

**3. In another NLP task, a model is developed to classify text documents into three
categories: Positive (pos), Neutral (neut), and Negative (neg). After deploying the
model on a test dataset, the following confusion matrix was recorded:
Using the confusion matrix above, calculate the following metrics: accuracy, and
precision, recall, F1 for each class. Then calculate the micro-average precision, recall**

```
Actual / Predicted      pos neut neg
                    pos  100  20 10
                    neut 330 120 20
                    neg   15  25 95
```

and F1. Finally calculate the macro-average precision, recall and F1 for the classifier.
Provide your answers in decimal form rounded to two decimal places.

In [34]:
confusion_matrix = np.array([
    [100, 20, 10],
    [330, 120, 20],
    [15, 25, 95]
])

def get_confusion_matrix_class(confusion_matrix, class_index):

    right_part = 0
    for col in range(confusion_matrix.shape[1]):
        if col != class_index:
            right_part += confusion_matrix[class_index, col]

    bottom_part = 0
    for row in range(confusion_matrix.shape[0]):
        if row != class_index:
            bottom_part += confusion_matrix[row, class_index]

    incliding_diagonal = 0
    for row in range(confusion_matrix.shape[0]):
        for col in range(confusion_matrix.shape[1]):
            if row != class_index and col != class_index:
                incliding_diagonal += confusion_matrix[row, col]
    

    return np.array([
        [confusion_matrix[class_index, class_index], right_part],
        [bottom_part, incliding_diagonal]
    ])

confusion_matrix_class_0 = get_confusion_matrix_class(confusion_matrix, 0)
confusion_matrix_class_1 = get_confusion_matrix_class(confusion_matrix, 1)
confusion_matrix_class_2 = get_confusion_matrix_class(confusion_matrix, 2)
print("confussion_matrix_class_0: ", "\n", confusion_matrix_class_0)
print("confussion_matrix_class_1: ", "\n", confusion_matrix_class_1)
print("confussion_matrix_class_2: ", "\n", confusion_matrix_class_2)

print("metric for class pos")
accuracy_pos, precision_pos, recall_pos, f1_pos = calculate_metrics(confusion_matrix_class_0)
print("metric for class neu")
accuracy_neu, precision_neu, recall_neu, f1_neu = calculate_metrics(confusion_matrix_class_1)

print("metric for class neg")
accuracy_neg, precision_neg, recall_neg, f1_neg = calculate_metrics(confusion_matrix_class_2)

macro_precision = (precision_pos + precision_neu + precision_neg) / 3
macro_recall = (recall_pos + recall_neu + recall_neg) / 3
macro_f1 = (f1_pos + f1_neu + f1_neg) / 3
print("macro_precision: ", macro_precision)
print("macro_recall: ", macro_recall)
print("macro_f1: ", macro_f1, "\n")

pooled_confussion_matrix = confusion_matrix_class_0 + confusion_matrix_class_1 + confusion_matrix_class_2

micro_accuracy, micro_precision, micro_recall, micro_f1 = calculate_metrics(pooled_confussion_matrix)

print("micro_accuracy: ", micro_accuracy)
print("micro_precision: ", micro_precision)
print("micro_recall: ", micro_recall)
print("micro_f1: ", micro_f1, "\n")


confussion_matrix_class_0:  
 [[100  30]
 [345 260]]
confussion_matrix_class_1:  
 [[120 350]
 [ 45 220]]
confussion_matrix_class_2:  
 [[ 95  40]
 [ 30 570]]
metric for class pos
accuracy:  0.4897959183673469
precision:  0.7692307692307693
recall:  0.2247191011235955
f1:  0.34782608695652173 

metric for class neu
accuracy:  0.46258503401360546
precision:  0.2553191489361702
recall:  0.7272727272727273
f1:  0.3779527559055118 

metric for class neg
accuracy:  0.9047619047619048
precision:  0.7037037037037037
recall:  0.76
f1:  0.7307692307692308 

macro_precision:  0.5760845406235477
macro_recall:  0.5706639427987743
macro_f1:  0.4855160245437548 

accuracy:  0.6190476190476191
precision:  0.42857142857142855
recall:  0.42857142857142855
f1:  0.42857142857142855 

micro_accuracy:  0.6190476190476191
micro_precision:  0.42857142857142855
micro_recall:  0.42857142857142855
micro_f1:  0.42857142857142855 



In [11]:
precision_pos = 100/130
precision_neu = 120/470
precision_neg = 95/135

recall_pos = 100/445
recall_neu = 120/165
recall_neg = 95/125

f1_pos = 2 * (precision_pos * recall_pos) / (precision_pos + recall_pos)#
f1_neu = 2 * (precision_neu * recall_neu) / (precision_neu + recall_neu)
f1_neg = 2 * (precision_neg * recall_neg) / (precision_neg + recall_neg)

print("precision_pos: ", precision_pos)
print("recall_pos: ", recall_pos)
print("f1_pos: ", f1_pos)

print("precision_neu: ", precision_neu)
print("recall_neu: ", recall_neu)
print("f1_neu: ", f1_neu)

print("precision_neg: ", precision_neg)
print("recall_neg: ", recall_neg)
print("f1_neg: ", f1_neg)

macro_precision = (precision_pos + precision_neu + precision_neg) / 3
macro_recall = (recall_pos + recall_neu + recall_neg) / 3
macro_f1 = (f1_pos + f1_neu + f1_neg) / 3
print("macro_precision: ", macro_precision)
print("macro_recall: ", macro_recall)
print("macro_f1: ", macro_f1)

precision_pos:  0.7692307692307693
recall_pos:  0.2247191011235955
f1_pos:  0.34782608695652173
precision_neu:  0.2553191489361702
recall_neu:  0.7272727272727273
f1_neu:  0.3779527559055118
precision_neg:  0.7037037037037037
recall_neg:  0.76
f1_neg:  0.7307692307692308
macro_precision:  0.5760845406235477
macro_recall:  0.5706639427987743
macro_f1:  0.4855160245437548


**4. Briefly explain what the bootstrap method is and why it is appropriate for comparing
two classifiers.**

The boostrap method is a method to create artificial test data sets from an observed test set in order to perform an non-parametric hypothesis testing.

It consists in creating artificial test data sets by sampling randomnly with replacement from a base (or reference) test data set. Under the assumption that the base sample is a representative of the population.

It's appropiate for comparing two classifiers because bootstrap normaly work with paired tests, which compare two sets of observations that somehow are aligned. When we analyze two classifier models A and B, the performance of A and B is paired by comparing them.




**5. Describe the steps you would take to apply the bootstrap method to compare Model
A and Model B.**

1. Measure the performance of metric $M$ in a base test set (size N) for the model A and B, and display the results.
2. Create artificial test results by ramdonly samplign with replacement from the results (of size N).
    - It is practically pick randomly with replacement one of those N results.
3. Repeat the process until complete a set of results of size N.
4. Repeat the process b times until generate b artificial test results.
5. One we have b artificial test sets, we can calculate our p-value as follows

$$\text{p-value}(x) = \frac{1}{b}\sum_{i=1}^{b}\left(\delta(x^{(i)}) - \delta(x) \geq \delta(x) \right)$$

$$\text{p-value}(x) = \frac{1}{b}\sum_{i=1}^{b}\left(\delta(x^{(i)}) \geq 2\delta(x) \right)$$

where $x$ is the base test set and $x^{(i)}$ are the artificial test sample from $x$, and

$$\delta(x) = M(A,x) - M(B,x)$$

is the performance difference from A and B of metric $M$

6. If $\text{p-value} < \alpha$, we can reject the null hypothesis $H_0: \delta(x) \leq 0$ and accept $H_1: \delta(x) > 0$. In other words, accept that A is better than B wrt the performance on $M$.